### ISSUE TITLE
Broken links atelier

### ISSUE THREAD

**Issue by evernat** [vertigo-io/vertigo-docs#18]
Des liens `atelier` sont cités deux fois dans la page Accès aux données :
https://vertigo-io.github.io/vertigo-docs/#/basic/dao
Les deux liens affichent "not found".

**Comment by NPi2Loup** [comment]
Merci pour l’intérêt que vous portez à la documentation Vertigo.
Effectivement ces liens sont présent pour une documentation à venir.
Ils seront complétés dès que possible.
En attendant, si vous avez des questions particulières n'hésitez pas à nous contacter directement.

PS : Nous avons mis en place un Discord pour ceux qui n'ont pas d'accès direct à l'équipe : [Vertigo.io](https://discord.gg/TGgKrfa)
